### ISSUE TITLE
1.20 update

### ISSUE THREAD

**Issue by Ultimushadow** [gitsh01/libertyvillagers#108]
Hey there, I was hoping for some information on porting plans for 1.20? I use this mod in my 1.19.4 server and enjoy its functionality, is there a plan to work on an update in the future?

**Comment by gitsh01** [comment]
Thanks for the reminder. Work has been crazy of late so I haven't had much time.

Fortunately it doesn't seem like there was a lot of changes between 1.19.4 and 1.20.1, so I was able to get it done tonight. I did a quick check and everything seems to be working, but please let me know if you see anything wrong.

It's uploaded to Modrinth and to Github. I attempted to upload it to Curseforge but I'm not sure it stuck, might have to do with the Curseforge virus thing they're dealing with. I'll attempt that again later if it doesn't show up.

**Comment by Ultimushadow** [comment]
Great, thanks a ton! I'll let you know if I find anything while testing, but like you said I don't think they changed too much between updates. Have a good one!
