### ISSUE TITLE
Kills server

### ISSUE THREAD

**Issue by rhewtani** [gitsh01/libertyvillagers#111]
I believe I have the server set up for this mod.  However, I get the same error in the console, no matter what I've tried.

22.08 18:08:49 [Server] main/WARN Error loading class: net/minecraft/class_5272 (java.lang.ClassNotFoundException: net/minecraft/class_5272)
22.08 18:08:49 [Server] main/WARN @Mixin target net.minecraft.class_5272 was not found libertyvillagers.mixins.json:ModelPredicateProviderRegistryMixin from mod libertyvillagers

**Comment by rhewtani** [comment]
Turns out this may be the server translations mod.  It seems to cap at 1.19.3.  Is there a replacedment for use with 1.20?

**Comment by gitsh01** [comment]
No, there's no replacement yet. However, you don't need the server translations unless you want to use the villagerstats command. Unfortunately with fabric there's no way of getting translatable text from the server without something like server-translations.

If you can find a substitute please let me know.

Fortunately forge works fine without it.
