### ISSUE TITLE
Request a new version

### ISSUE THREAD

**Issue by SadEPa0628** [gitsh01/libertyvillagers#115]
Please quickly update the version for 1.20.2, I really like this mod

The content is translated from Chinese. Please understand if there are any mistakes

**Comment by gitsh01** [comment]
Just pushed a version for 1.20.2 for forge and fabric. Note, I had odd errors on forge 48.0.14+. recommend 48.0.13.

**Comment by SadEPa0628** [comment]
Okay, thank you.
