### ISSUE TITLE
Villager lagging

### ISSUE THREAD

**Issue by Nikev2** [gitsh01/libertyvillagers#116]
For some reason my villagers are lagging and not walking normally. This should not be happing my ram is only at 30 percent when i removed the mod it stopped lagging. Here are my mods. Note im a villager fanatic lol

![image](https://github.com/gitsh01/libertyvillagers/assets/75125482/c3df7519-dd27-4d9d-ad8d-b12fedc52b95)

**Comment by SettingDust** [comment]
post spark profiling plz.

May relate 1.18.2 https://spark.lucko.me/AuGQbT8nuu
The iron golem is finding bells. I think the logic need something like cache or index

**Comment by Nikev2** [comment]
Nvm its due to me having soduim for some reason it doesn't like it when i have it for a bit
