### ISSUE TITLE
Start crash

### ISSUE THREAD

**Issue by zc1108aaa** [gitsh01/libertyvillagers#133]
[latest0.log](https://github.com/gitsh01/libertyvillagers/files/15464371/latest0.log)

**Comment by RayBlazar** [comment]
Same, I'd like to use this mod
[latest.log](https://github.com/user-attachments/files/15860318/latest.log)

**Comment by gitsh01** [comment]
This should be fixed now with 1.20.1 on Modrinth, let me know if it isn't working for you.
