### ISSUE TITLE
Fabric Versioning Issue on Modrinth

### ISSUE THREAD

**Issue by intothebeans** [gitsh01/libertyvillagers#138]
Currently the 1.20.6 update is marked as the latest update for Minecraft version 1.20.1 on Modrinth. I believe this may be causing confusion or other issues. 
![Screenshot 2024-07-30 163329](https://github.com/user-attachments/assets/be7e9a7b-a648-43c7-947a-dbf2f9d42cdc)

**Comment by gitsh01** [comment]
Thanks, fixed!
