### ISSUE TITLE
Latest 1.20.1 version crashes the game

### ISSUE THREAD

**Issue by Mortycio** [gitsh01/libertyvillagers#140]
https://mclo.gs/lkmFUTP

**Comment by Mortycio** [comment]
@gitsh01 I was told that version 1.0.15, marked on Modrinth as compatible with 1.20.1, is the issue. It was designed for 1.20.6, making it incompatible with previous versions. Can you confirm this?

**Comment by gitsh01** [comment]
I think it's fixed now and should be approved by Modrinth shortly. Please let me know if it isn't.
