### ISSUE TITLE
SUGGESTION: add some improvements to villagers' ai if possible

### ISSUE THREAD

**Issue by CyberSteve777** [gitsh01/libertyvillagers#2]
Although the current one is quite good, I suggest to take a look at [Sky villages][1] mod. In some cases, villagers either can't find job or fall from height.

[1]: https://www.curseforge.com/minecraft/mc-mods/sky-villages-fabric

**Comment by CyberSteve777** [comment]
![2022-11-04_19 45 14](https://user-images.githubusercontent.com/69720241/200030248-654b8765-3837-4e6c-b289-c4ce617e141c.png)
in this photo, for ex., villager usually stuck

**Comment by CyberSteve777** [comment]
seed for testing: -4693931934510397662
mc: 1.19.2

**Comment by gitsh01** [comment]
Interesting that the villager decided to pathfind behind the furnace instead right in front. It looks like there's a one block gap between the wall and the furnace, and then another block for the wall.

As for the villager getting stuck - they think trapdoors are always closed, so the fact that it's "open" in that screenshot (as part of the flower box) means they get confused and think they can't jump up onto the flowers.

I will try to take a look and see if I can figure out a solution for why the villager didn't go in front of the furnace, but instead three blocks behind. The trap door one though will be much more complicated to fix.

**Comment by CyberSteve777** [comment]
Also, villagers are acting strange at this place
![2022-11-06_12 29 55](https://user-images.githubusercontent.com/69720241/200163523-5f6de9e3-0f6f-4e02-884a-c6276257f946.png)

**Comment by Timolino456** [comment]
I noticed in my modded world that villagers have trouble with trapdoors blocking their way. They don't recognize it as an obstacle. There's probably more blocks that they have the same problem with.

**Comment by CyberSteve777** [comment]
> Interesting that the villager decided to pathfind behind the furnace instead right in front. It looks like there's a one block gap between the wall and the furnace, and then another block for the wall.
> 
> As for the villager getting stuck - they think trapdoors are always closed, so the fact that it's "open" in that screenshot (as part of the flower box) means they get confused and think they can't jump up onto the flowers.
> 
> I will try to take a look and see if I can figure out a solution for why the villager didn't go in front of the furnace, but instead three blocks behind. The trap door one though will be much more complicated to fix.

That also happens on plains armorer house though

**Comment by gitsh01** [comment]
I'll look into this. I haven't dug too deeply into the part of the pathfinding code that determines obstacles, but I'll give it a go. I have noticed villagers having trouble with moving from bottom slabs to stairs.

**Comment by gitsh01** [comment]
> > Interesting that the villager decided to pathfind behind the furnace instead right in front. It looks like there's a one block gap between the wall and the furnace, and then another block for the wall.
> > As for the villager getting stuck - they think trapdoors are always closed, so the fact that it's "open" in that screenshot (as part of the flower box) means they get confused and think they can't jump up onto the flowers.
> > I will try to take a look and see if I can figure out a solution for why the villager didn't go in front of the furnace, but instead three blocks behind. The trap door one though will be much more complicated to fix.
> 
> That also happens on plains armorer house though. In addition to this, I think there should be an optional setting for villagers to avoid fences as well.

FYI: Villagers already avoid fences with the maximum penalty of -1 by default (see net.minecraft.entity.ai.pathing.PathNodeType).

**Comment by gitsh01** [comment]
Ok so the person who made the skyvillages mod is being very cruel to the villagers. 
There's a wall on top of the blast furnace. The villager thinks it is not possible to path there because of the wall. Trying to figure out a solution.

**Comment by CyberSteve777** [comment]
> Ok so the person who made the skyvillages mod is being very cruel to the villagers. There's a wall on top of the blast furnace. The villager thinks it is not possible to path there because of the wall. Trying to figure out a solution.

Check vanilla plains armorer house and look at blast furnace here. You'll see same

**Comment by gitsh01** [comment]
Fixed in version 1.0.2.
