### ISSUE TITLE
1.18.2 Possible?

### ISSUE THREAD

**Issue by huerga1** [gitsh01/libertyvillagers#3]
Villager ai fixes is something I've wanted for some time now, but unfortunately it is 1.19 only. If possible, could 1.18.2 also be supported? Even if not updated would be very useful

**Comment by gitsh01** [comment]
Unlikely. I've got some features I'd like to add, then I plan on making sure it works with the 20 snapshots next so it's ready to go when the next release drops. So if I were to do this, it would be a while.

You are more than welcome to take up this task and back-port it to 1.18 :)

May I ask, why are you still on 1.18? What features keep you there?

**Comment by huerga1** [comment]
That's a shame, I hoped that this would not be to big an issue to port, and it would be a nice little mod to have. The reason I am still on 1.18 is not because of any particular features, but just because I started with it and many of the mods are still not in 1.19. Personally I think you should hold off ports for 1.20 just yet, because there is nearly no way that any of the big mods would have done so in time. I'd prefer you to take your time and release a port until most others have done so too or maybe just do 1.18 first instead, but I will be awaiting your response and then you can close it.

**Comment by gitsh01** [comment]
Fair enough, I will investigate and see how much work this will be.

**Comment by gitsh01** [comment]
It turned out to not be too much work. Ironically the hardest part was finding out the names of the types of cats since they redid their registration logic for cat variants in 1.19.

I've now pushed a version to curseforge and modrinth for 1.18.2.
