### ISSUE TITLE
Villagers and Rails

### ISSUE THREAD

**Issue by Timolino456** [gitsh01/libertyvillagers#33]
I'm not sure what villagers' behaviour in vanilla is supposed to be, but imo villagers should - like some monsters do it - avoid stepping on rails when possible.
I noticed that I had villagers walk around on my rail system, which connects the village to my house, multiple times.
It would be cool if you could add an option for villagers to avoid rails (which probably should be turned on by default).

In my case the current situation can actually be dangerous, because I use Cammie's Minecart Tweaks to increase maximum minecart speed a little, but it also adds damage on impact with a minecart at high speeds, which is 10 hearts exactly, able to kill villagers that are idiotic enough to think dancing around on my rails is funny. I almost killed a villager like that once already.

Making them avoid rails would also simply be more realistic.

Live footage of one of the incidents taken by local police:
![image](https://user-images.githubusercontent.com/38137599/206005006-7a0a2606-bfa7-4ba7-a940-1f849fb88c62.png)
And yes, before you might ask, I tested the same without the slabs in case that it might make a difference for their pathfinding.

**Comment by gitsh01** [comment]
Love this idea, I'll add it in the next build.    PathNodeType RAIL is already defined with a default of 0.0, I'll up it so they avoid rails.

**Comment by gitsh01** [comment]
Will be in 1.0.6.
