### ISSUE TITLE
Villagers seemlingly see their ticket to escape from the mortal world when near powdered snow

### ISSUE THREAD

**Issue by Timolino456** [gitsh01/libertyvillagers#41]
I was exploring my world, walking and swimming through an seemingly endless icy ocean for more than an hour already when I finally got to a snowy taiga. From afar, I saw a structure that looked like it would house villagers and so instantly walked towards it, while trying to avoid the hundreds of tons of powdered snow that were everywhere around me.
Before I even got close to the structure, I heard it: a villager screaming in pain, sunken in the cold powdered snow. I quickly made out where the sound was coming from and freed it with my shovel after also accidentally walking into it myself. I was proud of myself for saving a villagers life.
A few seconds later, I heard another villager screaming for help. I was also able to safe it just barely, almost dying myself in the process.
But minute after minute, more and more villagers seem to actively seek their demise, walking straight into the powdered snow, slowly freezing to death. I gave up on saving them, as it was apparently their wish to end their existence in this land of cold solitude.

What I'm trying to say: Can you please make villagers avoid powdered snow lol

**Comment by gitsh01** [comment]
Sounds like a good idea, it'll be in the next build.
