### ISSUE TITLE
Feature: Investigate porting to forge

### ISSUE THREAD

**Issue by gitsh01** [gitsh01/libertyvillagers#5]
There are several requests on curseforge for a forge port. Investigate how much work it will be to release a forge version.

**Comment by MikeTheBuddy** [comment]
Question, has any update on looking to port it to forge? I'm curious if there is any plans or progress regarding it.

**Comment by gitsh01** [comment]
I started working on porting it to architectaury in January. Unfortunately at that point my work went through layoffs and into crunch mode, and I've had little free time since. 

I accept pull requests, if you want to port it yourself, but I'm not sure when my schedule will allow me free time to code for fun right now. I'll accept either a straight port to forge or achitectuary. Most of the mixins should just go over, the tricky part is the UI for the stats book and the overlay.

**Comment by gitsh01** [comment]
I ported 1.18.2 to forge but it was a pretty big overhaul so I've marked it as beta. It's uploading now to curseforge and modrinth. 

Assuming no major issues I'll port it to the other versions soon.

Thank you for your patience, this turned out to be a very frustrating and time consuming task.

**Comment by MasterGordon** [comment]
Awesome work really looking forward to a 1.20 version for forge!

**Comment by gitsh01** [comment]
Just pushed a version for forge 1.20.1 and a different version for 1.20.2. Forge is unstable on 1.20.2, I recommend 48.0.13, something is really wrong with 48.0.14+.

Thank you for your patience.
