### ISSUE TITLE
Server crashing after updating to 1.0.7+1.19.2 from 1.0.6+1.19.2

### ISSUE THREAD

**Issue by ChristopherHaws** [gitsh01/libertyvillagers#54]
Here is the crash report: https://pastebin.com/7E6YyNez

**Comment by Timolino456** [comment]
Having the same issue: https://mclo.gs/o8iYo89

**Comment by gitsh01** [comment]
Looking into this now.

<html>
<body>


java.lang.ClassCastException: class com.google.common.collect.RegularImmutableMap cannot be cast to class it.unimi.dsi.fastutil.objects.Reference2ObjectOpenHashMap (com.google.common.collect.RegularImmutableMap and it.unimi.dsi.fastutil.objects.Reference2ObjectOpenHashMap are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @57baeedf)
--
8 | at net.minecraft.entity.ai.brain.task.Task.hasRequiredMemoryState(me/jellysquid/mods/lithium/mixin/ai/task/memory_change_counting/TaskMixin.java [lithium.mixins.json]:49)


</body>
</html>
