### ISSUE TITLE
New Feature: Iron golem will not walk away within x radius from bell

### ISSUE THREAD

**Issue by ChocoMartini** [gitsh01/libertyvillagers#55]
why would they leave the village, they didn't get paid enough?

**Comment by gitsh01** [comment]
I like this idea, I'll implement it soon. ;)

**Comment by gitsh01** [comment]
... wait, you're paying your golems? 

Dang, knew I was doing something wrong....

**Comment by gitsh01** [comment]
Will be added in the next release.
