### ISSUE TITLE
Golems are suddenly determined to wreck enemies that are dozens of blocks away

### ISSUE THREAD

**Issue by Timolino456** [gitsh01/libertyvillagers#77]
After updating to 1.0.9 I noticed that my two golems suddenly walked out of the village through the area that's still missing a wall, but I couldn't see any monsters.
Apparently they saw a zombie move only one of its rotten muscles in the shadow of a tree of the forest that is more than 50 blocks away from where the golems were starting from. After mercilessly killing it, they went on to kill a group of skeletons that also was more than 50 blocks away on the other side of the village. It seems like their agro range is suddenly way larger, which makes them run out of the village at night, where protection is actually needed.

**Comment by gitsh01** [comment]
Yikes! I have the surrounding countryside pretty lit up so I didn't notice this in my world. I'll look into this today.

**Comment by gitsh01** [comment]
It should be fixed in 1.0.10 which I just pushed today to modrinth/github/curseforge.

Thanks for your patience!
