### ISSUE TITLE
1.0.10 for 1.19.2 issue

### ISSUE THREAD

**Issue by LadySunx** [gitsh01/libertyvillagers#85]
I don't have a crash log to give you but when i updated to the latest version of liberty's villagers i would be stuck on the joining world screen and had to force close the game. So i downgraded it back to 1.0.9 and i was able to get into the world again no issues. If there is something i can send you let me know other than the crash report since it did not generate one.

**Comment by gitsh01** [comment]
Heyya, are you able to tell me what your default is for "Golems Move To Shore" range in 1.0.10? It should be low (~10), if not, hit the reset button to the right.

If that fixes it, I'll change the name of the config so that folks who got 1.0.9 early don't run into this problem.

**Comment by LadySunx** [comment]
> I just published a version 1.0.11 which has a fix for this, assuming it's the Golem Move To Shore causing trouble...

I will update and let you know just in case should i delete the mod and config then redownload?

**Comment by LadySunx** [comment]
> I just published a version 1.0.11 which has a fix for this, assuming it's the Golem Move To Shore causing trouble...

Aight so I deleted the mod and the config and redownloaded the newest version you posted and i was able to join the world. Thank you for the quick update and keep up the great work!!
