### ISSUE TITLE
When there aren't enough beds in a village, villagers would rather die instead of going into the safe indoors

### ISSUE THREAD

**Issue by Timolino456** [gitsh01/libertyvillagers#89]
I've observed this in a few naturally generated villages now, where there were just not enough beds for every villager. They simply don't go into any house at night.
I'm not sure if this is an issue of the mod or vanilla, although I remember them going indoors at night regardless in vanilla, but I might be misremembering there.

Using 1.0.11 for 1.19.3

CCTV footage attached:
![image](https://user-images.githubusercontent.com/38137599/211168879-f2384343-95f0-48bd-b293-3060c26cf8f5.png)

**Comment by gitsh01** [comment]
I will try to get to this this week. Thanks for finding this.

**Comment by gitsh01** [comment]
Should be fixed in 1.0.12, which I just uploaded. Thanks for the report!
