### ISSUE TITLE
Villagers don't approach to pick up foods

### ISSUE THREAD

**Issue by kuguo123** [gitsh01/libertyvillagers#94]
Villagers do not approach and pick up foods, such as potatoes and breads.

**Comment by kuguo123** [comment]
Is that a bug or not?

**Comment by kuguo123** [comment]
Without this mod ,they'll try to pick up them.

**Comment by gitsh01** [comment]
I'll try to look into it this weekend, it's been a very hectic week.

**Comment by gitsh01** [comment]
Can I get more details? Villagers are picking things up in 1.19.2, I'll go check 1.19.3 soon. 

They do have a pickup cooldown (in Mojang's code), so they only pick stuff up every 60 ticks, or 3 seconds.

**Comment by gitsh01** [comment]
Found the bug in 1.19.3. :( Will get a fix out soon.

**Comment by gitsh01** [comment]
Version 1.0.13 is now uploaded everywhere with this fix.
