### ISSUE TITLE
Stuck Villager Wandering Fix can make Villagers teleport out of their cages/houses you made for them.

### ISSUE THREAD

**Issue by ConqAra** [gitsh01/libertyvillagers#95]
For some reason there's a bug on my server with this mod on where villagers are teleporting through glass panes and iron doors and getting out of the house. I'm assuming this mod is the culprit with how it changes villager's behaviors. They do a endermen/teleport effect when they do it.

**Comment by kuguo123** [comment]
Try turning off Stuck Villager Wandering Fix.It can probably fix it.

**Comment by ConqAra** [comment]
works, thanks 👍

**Comment by gitsh01** [comment]
Hmm, yes this definitely is the stuck villager fix, but the question I have is why do the villagers think they can path that way. I'll need to investigate the pathfinding and see if iron bars and glass panes are marked as impassible.

**Comment by ConqAra** [comment]
> Hmm, yes this definitely is the stuck villager fix, but the question I have is why do the villagers think they can path that way. I'll need to investigate the pathfinding and see if iron bars and glass panes are marked as impassible.

For me it was glass panes and iron doors. Had to put a fence around the house until I turned off Stuck Villager Wandering Fix

**Comment by gitsh01** [comment]
Found the issue. Iron doors were already being checked for pathfinding, but glass panes weren't. 

Adding an option for the villagers to avoid glass panes in the next version, which prevents them from trying to "path" through the glass panes.

**Comment by gitsh01** [comment]
Version 1.0.13 will have this fixed. :) Thanks for the report.
